package commands;

public enum CommandNamesEnum {
    CLEAR,
    EXECUTE_SCRIPT,
    EXIT,
    GROUP_COUNTING_BY_PERSONAL_QUALITIES_MAXIMUM,
    HELP,
    INFO,
    INSERT,
    PRINT_DESCENDING,
    REMOVE_ANY_BY_PERSONAL_QUALITIES_MAXIMUM,
    REMOVE_GREATER_KEY,
    REMOVE_KEY,
    REPLACE_IF_GREATER,
    REPLACE_IF_LOWER,
    SAVE,
    SHOW,
    UPDATE
}
